services:
  backend:
    image: node:latest
    container_name: urbango-backend
    env_file: .env
    environment:
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
    ports:
      - 8080:8080
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./src/server:/app/src/server
    working_dir: /app
    command: bash -c "npm install && npm run dev"

  frontend:
    image: node:latest
    container_name: urbango-frontend
    env_file: .env
    environment:
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
    ports:
      - 80:80
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./index.html:/app/index.html
      - ./public:/app/public
      - ./src/client:/app/src/client
    working_dir: /app
    depends_on:
      - backend
    command: bash -c "npm install && npm run dev:client"
